# Generated by Django 4.1.3 on 2023-02-22 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('region', models.CharField(blank=True, max_length=10, null=True)),
                ('location', models.CharField(blank=True, max_length=20, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='picture')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=9, null=True, region=None)),
                ('profession', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
