# Generated by Django 4.1.3 on 2023-03-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_email_register_username_alter_register_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='found',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img_found'),
        ),
    ]
