# Generated by Django 4.1.3 on 2022-11-24 21:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=24)),
                ('location', models.CharField(max_length=20)),
                ('mention', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='pictures')),
                ('desc', models.CharField(max_length=256)),
                ('date_created', models.DateTimeField(verbose_name=datetime.datetime(2022, 11, 24, 22, 32, 19, 930493))),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
